# This file was generated by GoReleaser. DO NOT EDIT.
cask "container-use" do
  desc "Containerized environments for coding agents"
  homepage "https://github.com/cwlbraa/container-use"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cu"
  bash_completion "completions/cu.bash"
  zsh_completion "completions/cu.zsh"
  fish_completion "completions/cu.fish"

  on_macos do
    on_intel do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.0.6/container-use_v0.0.6_darwin_amd64.tar.gz"
      sha256 "79aabf050f7f186037d6ffc98f0acc87d1af22936c3ea081eeb530d58184c887"
    end
    on_arm do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.0.6/container-use_v0.0.6_darwin_arm64.tar.gz"
      sha256 "3246273a63e78cc7284d4d4bb6438c91a4a4c06dde43e300dc4cfd141062ed9a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.0.6/container-use_v0.0.6_linux_amd64.tar.gz"
      sha256 "3bb24c76e02476a88dac8db5ca52cbcfe35609b79cdd12b76c5010fed276d449"
    end
    on_arm do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.0.6/container-use_v0.0.6_linux_arm64.tar.gz"
      sha256 "de007a558ece7fa67a6af871a1877297c2f3ced62a6ed1621e71345f310de508"
    end
  end

  postflight do
    # remove quarantine xattr (note we don't do anything with signatures yet)
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cu"]
    end
  end

  # No zap stanza required
end
