# This file was generated by GoReleaser. DO NOT EDIT.
cask "container-use" do
  desc "Containerized environments for coding agents"
  homepage "https://github.com/cwlbraa/container-use"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "container-use"
  bash_completion "completions/container-use.bash"
  zsh_completion "completions/container-use.zsh"
  fish_completion "completions/container-use.fish"

  on_macos do
    on_intel do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.2.0/container-use_v0.2.0_darwin_amd64.tar.gz"
      sha256 "afac7035a97ae5f6714252fe60b3c3478b9301d181d476b204bc3163379c5fae"
    end
    on_arm do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.2.0/container-use_v0.2.0_darwin_arm64.tar.gz"
      sha256 "8181650d3ffb8006dbb9e394d0e7ad8f198f83e24b8eaa37b599cb9c938f3171"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.2.0/container-use_v0.2.0_linux_amd64.tar.gz"
      sha256 "5be6fbce0c47b12081b8c98f7ee1d584ac5b678f7e9d2e2c99ef4e2ffde95b44"
    end
    on_arm do
      url "https://github.com/cwlbraa/container-use/releases/download/v0.2.0/container-use_v0.2.0_linux_arm64.tar.gz"
      sha256 "0b5f2d08fb15c6d1976f64b9dffa20ed5445b36d88b53f1850e75d62138a5bd8"
    end
  end

  postflight do
    # remove quarantine xattr (note we don't do anything with signatures yet)
    if File.exist?("/usr/bin/xattr")
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/container-use"
    end

    # Create cu symlink for backward compatibility
    FileUtils.ln_sf "container-use", "#{staged_path}/cu"

    # Install cu completions for backward compatibility
    bash_completion = "#{HOMEBREW_PREFIX}/etc/bash_completion.d"
    zsh_completion = "#{HOMEBREW_PREFIX}/share/zsh/site-functions"
    fish_completion = "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"

    if File.exist?("#{staged_path}/completions/cu.bash")
      FileUtils.mkdir_p bash_completion
      FileUtils.cp "#{staged_path}/completions/cu.bash", "#{bash_completion}/cu"
    end

    if File.exist?("#{staged_path}/completions/cu.zsh")
      FileUtils.mkdir_p zsh_completion
      FileUtils.cp "#{staged_path}/completions/cu.zsh", "#{zsh_completion}/_cu"
    end

    if File.exist?("#{staged_path}/completions/cu.fish")
      FileUtils.mkdir_p fish_completion
      FileUtils.cp "#{staged_path}/completions/cu.fish", "#{fish_completion}/cu.fish"
    end
  end

  # No zap stanza required
end
